options:
  adminKeyHash:
    type: string
    default: ""
    description: "webapi key hash for communicating with the webapi. Cannot be changed after the setting it up"
  guiPassword: 
    type: string
    default: ""
    description: "password for the admin gui interface"
  zrayEnable:
    type: boolean
    default: false
    description: "Set to true to enable zray on each request"
