#!/bin/bash
set -e # If any command fails, stop execution of the hook with that error
adminKey=`config-get adminKey`
adminKeyHash=`config-get adminKeyHash`
#/usr/local/zend/bin/zs-manage  restart-php -N $adminKey -K $adminKeyHash
#php bin/zs-client.php installApp --zpk="<location-of-the-zpk-file>" --target="<the-name-of-the-target>" --baseUri="<baseUri>"
#open-port 80
#open-port 10082
#open-port 10081
