#!/bin/bash
set -e # If any command fails, stop execution of the hook with that error
db_user=`relation-get user`
#db_db=`relation-get database`
db_pass=`relation-get password`
db_host=`relation-get private-address`
adminKeyHash=`relation-get adminKeyHash`
adminKey=`relation-get adminKey`
magento_admin_password="1234"
magento_admin_email="admin@localhost.com"
port=80
if [ -z "$adminKeyHash" ]; then
	juju-log "No Zend server admin webapi key set by peer relation getting the key from the config"
	adminKey=`config-get adminKey`
	adminKeyHash=`config-get adminKeyHash`
fi
if [ -z "$db_pass" ]; then
  juju-log "No database information sent yet. Silently exiting"
  exit 0
fi
sudo apt-get install mysql-client -y
private_address=`unit-get private-address`
public_address=`unit-get public-address`
add_command="/usr/local/zend/bin/zs-manage server-add-to-cluster -n $JUJU_UNIT_NAME-$public_address -i $private_address  -o $db_host -u $db_user -p $db_pass -d ZendServer -r 60 -w 5 -s -N $adminKey -K $adminKeyHash"
juju-log "adding ZS to cluster with $add_command"
eval $add_command
juju-log "Adding vhost $public_address"
/usr/local/zend/bin/zs-manage vhost-add -n $public_address -p $port -N $adminKey -K $adminKeyHash
if [[ ! -z "`mysql -u"$db_user" -p"$db_pass" -h "$db_host" -qfsBe "SELECT SCHEMA_NAME FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME='magento'" 2>&1`" ]];
then
  juju-log "magento DATABASE ALREADY EXISTS will not proceed with installing apps"
else
  juju-log "Enabling Zend server Session Clustering"
  /usr/local/zend/bin/zs-manage store-directive -d 'zend_sc.ha.use_broadcast' -v '0' -N "$adminKey" -K "$adminKeyHash"
#  /usr/local/zend/bin/zs-manage store-directive -d 'session.save_handler' -v 'cluster' -N "$adminKey" -K "$adminKeyHash"
  /usr/local/zend/bin/zs-manage store-directive -d 'zend_sc.enable' -v '1' -N "$adminKey" -K "$adminKeyHash"
  juju-log "No Magento DB. Installing the apps"
  app_url="http://$public_address/magento" 
  sudo sed -i 's/memory_limit = .*M   /memory_limit = 789M   /g' /usr/local/zend/gui/lighttpd/etc/php-fcgi.ini
  deploy="/usr/local/zend/bin/zs-manage app-deploy --pkgFile "files/magento-1.7.zpk" --baseUrl "$app_url" --userParams \"site_url="$app_url" db_host="$db_host" db_username="$db_user" db_password="$db_pass" db_name="magento" admin_password="$magento_admin_password"\"  -N $adminKey -K $adminKeyHash"
  juju-log "deploying Magento application on Zend Server with $deploy command"
  eval $deploy
  sudo sed -i 's/memory_limit = .*M   /memory_limit = 128M   /g' /usr/local/zend/gui/lighttpd/etc/php-fcgi.ini
  app_url="http://$public_address/wordpress"
  deploy="/usr/local/zend/bin/zs-manage app-deploy --pkgFile "files/wordpress-3.9.1.zpk" --baseUrl "$app_url" --userParams \"site_url="$app_url" db_host="$db_host" db_username="$db_user" db_password="$db_pass" db_name="wordpress" admin_password="$magento_admin_password"\" -N $adminKey -K $adminKeyHash"
  app_url="http://$public_address/demo"
  juju-log "deploying $app_url  on Zend Server with $deploy command"
  eval $deploy
  deploy="/usr/local/zend/bin/zs-manage app-deploy --pkgFile "files/demo.zpk" --baseUrl "$app_url"  -N $adminKey -K $adminKeyHash"
  juju-log "deploying demo application on Zend Server with $deploy command"
  eval $deploy
fi
