#!/bin/bash
set -ex # If any command fails, stop execution of the hook with that error
echo "ZS_installed=false" >> ~/.ZendServerStatus
#tar xzf files/repo_installer_early_access.tar.gz
tar xzf files/repo_installer_beta.tar.gz
