#!/bin/bash
set -e # If any command fails, stop execution of the hook with that error
phpVersion=`config-get phpVersion`
adminKeyHash=`config-get adminKeyHash`
guiPassword=`config-get guiPassword`
orderNumber=`config-get orderNumber`
licenseKey=`config-get licenseKey`
production=`config-get production`
adminKey="adminKey"
if [ -z "$adminKeyHash" ]; then
        adminKeyHash=`date +%s | sha256sum | base64 | head -c 64`
        juju-log  --log-level WARNING "Missing web api key in config.yaml. Generated $adminKeyHash as the key. This is fine in single server scenario but will not work in clustered scenario"
fi
juju-log "using Zend server webapi key name '$adminKey' and webapi key hash $adminKeyHash"
tar xzf files/repo_installer_nightly_cloud_repo.tar.gz
./install_zs.sh $phpVersion --automatic
/usr/local/zend/bin/zs-manage api-keys-add-key -n $adminKey -s $adminKeyHash
bootstrap="/usr/local/zend/bin/zs-manage bootstrap-single-server -p $guiPassword -a TRUE   -r $production "
if [ -n "$licenseKey" ]; then
	bootstrap="$bootstrap -o  $orderNumber -l $licenseKey"
fi
juju-log "Will bootstrap Zend server with $bootstrap"
eval $bootstrap
/usr/local/zend/bin/zs-manage  restart-php -N $adminKey -K $adminKeyHash
